Feature imprvt
desihub/prospect pull request #58
Opened 2021-01-08 11:24 UTC by armengau

Better to merge this now, and start another branch.
This adds a simple bug fix, and an additional feature = an optional countdown widget.

2021-01-08 16:01 UTC, weaverba137 requested changes
For the record, I think "speed redshifting" is not scientifically useful.  Why *encourage* people to be hasty and sloppy in the visual inspection process?

However, I don't see any problems with the code itself, besides the import statement I will need to test.  I assume you have tested this in a notebook?

Please add a comment to the change log file.

2021-01-08 16:19 UTC, armengau commented on py/prospect/mycoaddcam.py
> +from desispec.interpolation import resample_flux
I do not disagree on the countdown, this was a request. The code is such that no line is added to the js code when vi_countdown=-1.

Just to make sure about change log: I shall add a line for version 1.0.2, but this version remains unreleased, and only prospect._version is changed after the merge, right?

2021-01-08 16:21 UTC, armengau commented on py/prospect/mycoaddcam.py
> +from desispec.interpolation import resample_flux
You're right, in mycoaddcam  try:.. except ImportError: pass  should probably be added.
Should I do that now ?

2021-01-08 17:06 UTC, weaverba137 commented on py/prospect/mycoaddcam.py
> +from desispec.interpolation import resample_flux
Yes, you should add the change log comment under the unreleased version 1.0.2.  That is what it is there fore.

You can go ahead and add the `try:`, but I will need to test it.

2021-01-08 20:25 UTC, armengau commented on py/prospect/mycoaddcam.py
> +from desispec.interpolation import resample_flux
I added the try + a related change in plotspecutils so that desispec's resample_flux is not used there.

2021-01-08 22:54 UTC, weaverba137 commented on doc/changes.rst
> +* Optional countdown widget
Please follow the format of the other change log entries.  In particular, almost all change log entries are associated with a pull request.

2021-01-08 22:56 UTC, weaverba137 commented on py/prospect/plotframes.py
> +                var looop = setInterval(function(){
Is there a particular reason the variable is called `looop`?  Deliberate misspellings are kind of dangerous in practice, especially in JavaScript which is not especially strict about variable definition.

2021-01-09 17:18 UTC, armengau commented on doc/changes.rst
> +* Optional countdown widget
Done

2021-01-09 17:21 UTC, armengau commented on py/prospect/plotframes.py
> +                var looop = setInterval(function(){
No good reason => variable name changed.

2021-01-09 17:46 UTC, weaverba137 approved these changes

2021-01-09 17:46 UTC, weaverba137 commented
Thanks @armengau, merge when ready.

2021-01-09 18:23 UTC, armengau commented
@weaverba137 Should I edit prospect._version (keep 1.0.1 but change num to 33X) and commit "bump version" in master after the merge ?

2021-01-09 19:24 UTC, weaverba137 commented
No, the only time to change that is *after* a tag, not before.

2021-01-11 09:11 UTC, merged